import Head from 'next/head';
import HomePage from '../components/home'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Tailwind Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomePage />
      </main>
    </div>
  )
}
